# Pose offsets
# Broadcasted pose values of different birds when they are actually perfectly level
# Position and orientation offsets are SEPARTELY INVERTED, i.e., orientation is inverted locally, and position is inverted globally
charlie_1:
  position:
    x: 0.0
    y: 0.0
    z: 0.09
  orientation:
    x: 0.445
    y: 0.209
    z: -0.532
    w: 0.689

charlie_2:
  position:
    x: 0.0
    y: 0.0
    z: 0.09
  orientation:
    x: 0.03
    y: 0.01
    z: 0.04
    w: 0.999

charlie_3:
  position:
    x: 0.00
    y: 0.0
    z: 0.099
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
  # orientation:
  #   x: -0.5
  #   y: 0.5
  #   z: -0.5
  #   w: 0.5
  # orientation:
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   w: 1.0